/* Instructions to run the code:
    1. Download the file ass1.c.
    2. Open the terminal in the directory the C file has been downloaded.
    3. Type and enter gcc -o ass1 ass1.c to compile the code and create an executable.
    4. Run the executable by the command .\ass1 (in Windows terminal) or ./ass1 (in Linux terminal).
    5. The program file will start running. Follow the on-screen instructions to proceed further.*/

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>

// Modifies binary string 'a' by XORing it with binary string 'b'
void get_xor(char *a, char *b){
    for(int i=0; i<strlen(b); i++) a[i] = (a[i]==b[i]) ? '0' : '1';
}

// Computes the CRC bits for the given message and divisor
char* get_crc(char *data, char *div){
    int k = strlen(data);
    int p = strlen(div);

    char tmp[256];
    strcpy(tmp, data);
    for(int i=0; i<p-1; i++) tmp[k+i] = '0';
    tmp[k+p-1] = '\0';
    
    for(int i=0; i<k; i++){
        if(tmp[i]=='1') get_xor(tmp+i, div);
    }

    char *crc = (char*) malloc(p*sizeof(char));
    strcpy(crc, tmp+k);

    return crc;
}

// Generates frame of tranmission for the given message and divisor
char *get_frame(char *data, char *div){
    char *crc = get_crc(data, div);
    char *frame = (char*) malloc((strlen(data)+strlen(div)) * sizeof(char));
    strcpy(frame, data);
    strcat(frame, crc);

    return frame;
}

// Generates a random binary string of length 'len'
char* gen_data(int len){
    int random = rand() % ((1<<len) - (1<<(len-1))) + (1<<(len-1));
    char *data = (char*) malloc((len+1)*sizeof(char));
    for(int i=len-1; i>=0; i--){
        data[len-i-1] = ((random>>i) & 1) + '0';
    }
    data[len] = '\0';

    return data;
}

// Generates random bit errors in the given frame
char* gen_error(char *frame){
    char *error = (char*) malloc((strlen(frame)+1) * sizeof(char));
    strcpy(error, frame);

    int num = rand()%3;    // Number of error bits (0, 1 or 2)
    for(int i=0; i<num; i++){
        int pos = rand() % strlen(error);   //Choose a random bit to flip
        error[pos] = (error[pos]=='1') ? '0' : '1';
    }

    return error;
}

// Checks if the received frame is valid by performing the same division process
char check(char *frame, char *div){
    int n = strlen(frame);
    int p = strlen(div);
    char tmp[n+1];
    strcpy(tmp, frame);

    for(int i=0; i<=n-p; i++){
        if(tmp[i]=='1') get_xor(tmp+i, div);
    }

    for(int i=n-p+1; i<n; i++) {
        if(tmp[i]=='1') return 0; // DISCARD
    }

    return 1; // ACCEPT
}

int main1(){
    printf("\nCyclic Redundancy Check (CRC) Generator\n");
    char data[128], div[128];
    printf("Enter the data block (D) of at most 100 bits: ");
    scanf("%s", data);
    printf("Enter the CRC pattern (P) of at most 100 bits: ");
    scanf("%s", div);

    char *frame = get_frame(data, div);
    char *crc = frame + strlen(data);
    printf("\nThe generated CRC bits are: %s\n", frame + strlen(data));
    printf("The generated frame for transmission is: %s\n", frame);

    return 0;
}

int main2(){
    printf("\nSimulating Transmission with Errors\n");
    srand(time(NULL));

    char *data = gen_data(10);
    char *div = "110101";
    char *frame = get_frame(data, div);
    char *error = gen_error(frame);

    printf("\nSender Side:\n");
    printf("Message generated: %s\n", data);
    printf("CRC pattern used: %s\n", div);
    printf("CRC bits generated by sender: %s\n", frame + strlen(data));
    printf("Frame generated by sender: %s\n", frame);

    printf("\nReceiver Side:\n");
    printf("Frame received by receiver: %s\n", error);
    printf("Checking for errors...\n");
    if(check(error, div)) printf("Verdict: No errors found in frame. ACCEPT\n");
    else printf("Verdict: Errors found in frame. DISCARD\n");

    return 0;
}

int main(){
    int choice;
    printf("Choose an option:\n0. Exit\n1. Generate CRC and Frame\n2. Simulate Transmission with Errors\n");
    scanf("%d", &choice);

    if(choice==0) return 0;
    else if(choice==1) return main1();
    else if(choice==2) return main2();
    else{
        printf("\nInvalid choice.\n");
        return 0;
    }
}